[package]
name = "jstart"
version = "0.1.0"
authors = ["N4tus <mueker.ben@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"